name: 'amit_dbt_project'
version: '1.0.0'
config-version: 2

# هنا لازم يتطابق مع اسم الـ profile في profiles.yml
profile: 'Amit_pr'  

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  amit_dbt_project:
    # أي models في فولدر example هتتبني كـ view
    example:
      +materialized: view
